terasolunaorg/terasoluna-gfw-web-multi-blank

projectName-initdb/pom.xml

#146: Change to use absolute path as db.basedir at initdb

---

projectName-initdb/pom.xml

(cherry picked from commit a6b42e2de20c9bdb1e5193e6f339898b9409b0f3)
Please review #146 .

[5.0.x] #146: Change to use absolute path as db.basedir at initdb

---

infra/jpa/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
infra/mybatis3/projectName-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
infra/mybatis3/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
infra/mybatis3/projectName-domain/src/main/resources/xxxxxx/yyyyyy/zzzzzz/domain/repository/sample/SampleRepository.xml
projectName-domain/src/main/resources/META-INF/spring/projectName-codelist.xml
projectName-domain/src/main/resources/META-INF/spring/projectName-domain.xml
projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
projectName-domain/src/test/resources/test-context.xml
projectName-env/src/main/resources/META-INF/spring/projectName-env.xml
projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
projectName-web/src/main/resources/META-INF/spring/applicationContext.xml
projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
projectName-web/src/main/resources/META-INF/spring/spring-security.xml
projectName-web/src/main/webapp/WEB-INF/tiles/tiles-definitions.xml
projectName-web/src/main/webapp/WEB-INF/web.xml

Polishing XML files #185

---

projectName-selenium/pom.xml
projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java

Please review #175
* `mvn test` -> Normal JUnit tests run (except for `**/*IT.java`)
* `mvn integration-test` -> Selenium tests run (`**/*IT.java`)

Add maven-failsafe-plugin to prevent selenium testing in case of  maven install/package #175

---

pom.xml
projectName-selenium/pom.xml

---
#209
please review
by btokadanob
---

add maven-failsafe-plugin version definition #209

---

projectName-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/csrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html

Conflicts:
projectName-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
This PR is backport for 1.0.x .
Conflicts happened because `accessDeniedError.jsp` and `missingCsrfTokenError.jsp` do not exist in 1.0.x .

[1.0.x] add br tag to make the error page size 513 bytes or more #361

---

projectName-env/src/main/resources/logback.xml

(cherry picked from commit c32a6ab9ad267434a9d8446ad8b727ea88970a7e)
Please review #332 .
This PR is backport for 5.2.x .

[5.2.x] add doctype.#332

---

projectName-env/src/main/resources/logback.xml

(cherry picked from commit c32a6ab9ad267434a9d8446ad8b727ea88970a7e)
Please review #332 .
This PR is backport for 5.1.x .

[5.1.x] add doctype.#332

---

projectName-env/src/main/resources/logback.xml

(cherry picked from commit c32a6ab)
Please review #332.
This PR is backport for 5.0.x .

[5.0.x] add doctype.#332

---

projectName-env/src/main/resources/logback.xml

(cherry picked from commit c32a6ab)
Please review #332 .
This PR is backport for 1.0.x .

[1.0.x] add doctype.#332

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348

---

pom.xml

(cherry picked from commit f49f933f3c3251ed64bbdc605dbd4685d08e282e)
Please review #457.

remove a definition referring to Sonatype Nexus Snapshots #457 (#458)

---

pom.xml
projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

Please review #489.
Oracle JDBC Driver's groupId has bean changed from `com.oracle.ojdbc` to `com.oracle.database.jdbc`.

Change the groupId of the OracleJDBCDriver #489

---

projectName-web/pom.xml

Please review #494
Confirmation method：
I ran `mvn dependency: tree` and confirmed that the scope of the following libraries changed from `compile` to `runtime`.
I also confirmed that there were no unexpected changes.
- taglibs-standard-jstlel
- taglibs-standard-spec
- taglibs-standard-impl
I confimed the above library is not added to the classpath when I run `mvn -DincludeScope=compile dependency:build-classpath` but is added to the classpath when I run `mvn -DincludeScope=runtime dependency:build-classpath` .

set runtime scope in jstlel #494

---

projectName-web/pom.xml

(cherry picked from commit 141670bc4fc706dab9052b06937c745a92e1b06f)
Please review #498
Confirmation method：
I ran `mvn dependency: tree` and confirmed that the scope of the following libraries changed from `compile` to `runtime`.
I also confirmed that there were no unexpected changes.
- taglibs-standard-jstlel
- taglibs-standard-spec
- taglibs-standard-impl
I confimed the above library is not added to the classpath when I run `mvn -DincludeScope=compile dependency:build-classpath` but is added to the classpath when I run `mvn -DincludeScope=runtime dependency:build-classpath` .

[5.6.x]set runtime scope in jstlel #498

---

projectName-web/pom.xml
projectName-web/src/main/webapp/WEB-INF/web.xml

Please review #501 .
The only library included in the following section is Apache Taglibs, which is inappropriate because it is an implementation of the JSTL specification.The name of this section itself has been removed as it is not necessary to include it.
> <-- JavaEE/SE APIs -->

update Servlet API, jsp API. #501

---

pom.xml

Please review #514.
There was a local warning `JAR will be empty ~`, but this is a problem with the file structure under `src`, not dependent on the version of the plugin, so it is not handled.
(The above warning does not occur in the build job on gitlab.)
Confirmation:
Check for new warnings or errors due to upgrading plug-ins.
- `maven-war-plugin` : Confirmed that war generation succeeds without warning when `mvn package` is executed.
- `build-helper-maven-plugin` : Confirmed that the source directory is added successfully without any warnings when the project is built.
- `maven-failsafe-plugin` : Confirmed that the Test Result Report is generated without any warning when the test is executed.
- `maven-surefire-plugin` : Configured, but not used in the project, so not tested.

Update the version of the maven plugin #514

---

pom.xml

(cherry picked from commit bac84048b6367d70103c959508112aeaf196fd76)
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/516.
Confirmation:
- I did a Grep search for plugin to see if there was any other place that managed the plugin version other than the place where I imported it with cherry-pick.
- Check for new warnings or errors due to upgrading plug-ins.
- `maven-war-plugin` : Confirmed that war generation succeeds without warning when `mvn package` is executed.
- `build-helper-maven-plugin` : Confirmed that the source directory is added successfully without any warnings when the project is built.
- `maven-failsafe-plugin` : Confirmed that the Test Result Report is generated without any warning when the test is executed.
- `maven-surefire-plugin` : …

[5.6.x]Update the version of the maven plugin #514 (#515)

---

projectName-web/src/main/webapp/WEB-INF/web.xml

Please review #522 .
Confirmation
Confirmed that the addition of the setting causes the output of the log on destroy, which was not output before the modification.

Added a setting for log output when destroy is executed #522

---

projectName-web/src/main/webapp/WEB-INF/web.xml

Please review #522 
https://github.com/terasolunaorg/terasoluna-gfw-web-blank/pull/475#discussion_r570009799
Responding to comments on the link.
Confirmation
Confirmed that the addition of the setting causes the output of the log on destroy, which was not output before the modification.

Change the order of web.xml settings. #522

---

pom.xml

Please review #493 
Confirmed that javadoc can be generated by `mvn javadoc:javadoc` using jdk8 and jdk11
Check the following versions for jdk11:
openJDK 11+28
openJDK 11.0.5+10-LTS

set source to maven-javadoc-plugin #493

---

projectName-web/src/main/webapp/WEB-INF/web.xml

Please review #529 .
Confirmation
- Confirmed that the addition of the setting causes the output of the log on destroy, which was not output before the modification.

[5.6.x]Added a setting for log output when destroy is executed #522

---

parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java

Please review #613
`HttpSecurity#formLogin()`,`HttpSecurity#logout()`,`HttpSecurity#sessionManagement()` without arguments are now deprecated.
Therefore, empty methods are set as arguments.
https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/builders/HttpSecurity.html#formLogin()

fixed deprecated methods #613

---

pom.xml

Please review #652
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-3954
For httpclient5, the version managed by Spring-boot conflicts with the version on which webdrivermanager depends, so the version is set in pom.xml.

[5.7.x] library version up #652
