projectName-domain/pom.xml
projectName-env/src/main/resources/META-INF/spring/projectName-env.xml

add terasoluna-gfw-jodatime & replace DefaultDateFactoru -> DefaultJodaTimeDateFactory #86

---

README.md
pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

reversion 1.1.0 -> 5.0.0 #88

---

create-maven-archetype.sh

Modified the logic that replace directory path in create-maven-archetype.sh. #90

---

projectName-env/pom.xml

Corresponding leakage in projectName-env/pom.xml.
Please review #86 .

Added the dependency of terasoluna-gfw-jodatime. #86

---

projectName-env/pom.xml

Corresponding leakage in projectName-env/pom.xml.
Please review #2 .

Added the dependency of terasoluna-gfw-mybatis3. #2

---

projectName-env/pom.xml
projectName-web/pom.xml

Improved JDBC driver dependency settings. #92

---

projectName-domain/pom.xml

Sorry,fixed the corresponding leakage.
Please review #92 .

Removed the H2 database dependency from projectName-domain/pom.xml. #92

---

projectName-domain/pom.xml
projectName-env/pom.xml
projectName-web/pom.xml

Backported to 1.0.x from #93 & #96 .
Please review #92 .

[1.0.x] Improved JDBC driver dependency settings. #92

---

pom.xml
projectName-env/pom.xml

polished pom.xml #78

---

projectName-web/src/main/resources/ValidationMessages.properties

Please review #99, and merge to master branch.

Added ValidationMessages.properties #99

---

create-maven-archetype-jpa.sh
create-maven-archetype-mybatis2.sh
create-maven-archetype-mybatis3.sh
pom.xml

changed description #101

---

create-maven-archetype-jpa.sh
create-maven-archetype-mybatis2.sh

modified sed #106

---

README.md

update readme #108

---

pom.xml

#112 
added build-helper-maven-plugin

added build-helper-maven-plugin #112

---

pom.xml

* Delete dependency definitions for override the scope. (scope specify at each projects)
* Delete version properties for customization because it is incomplete settings.
Please review #114 .

Update dependencyManagement to apply terasolunaorg/terasoluna-gfw#267. #114

---

pom.xml

Sorry.. there are corresponding leakage.
Please review again #114 .

Add version property of build-helper-maven-plugin. #114

---

projectName-domain/pom.xml
projectName-env/pom.xml
projectName-env/src/main/resources/META-INF/spring/projectName-env.xml
projectName-env/src/main/resources/logback.xml

remove mybaits2 #117

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

Upgrade Version to 5.1.0-SNAPSHOT.
please review #120

Upgrade Version to 5.1.0-SNAPSHOT. #120

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

Upgrade Version to 5.0.1-SNAPSHOT. #121

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

Upgrade Version to 1.0.3-SNAPSHOT. #122

---

projectName-env/src/main/resources/META-INF/spring/projectName-env.xml

Specify encoding as UTF-8. #131

---

projectName-env/src/main/resources/logback.xml

Use property to resolve a log output directory. #126

---

projectName-web/src/main/webapp/WEB-INF/views/layout/header.jsp

Please review #110, and merge to master branch.

possible to link to toppage #110

---

projectName-web/src/main/webapp/WEB-INF/views/layout/header.jsp

(cherry picked from commit 57669b28eb9f5adec1d3529457cc2b72a3ec7de7)
I backported ot 5.0.x.
Please review #110 .

[5.0.x] possible to link to toppage #110

---

CONTRIBUTING.md

please review CONTRIBUTING.md #128

add CONTRIBUTING.md #128

---

.gitignore

#148: Ignore IDEA project file from git management

---

projectName-domain/src/test/resources/test-context.xml

* bean definition of <property-placeholder>
* bean definition of ExceptionLogger
Please review #147 .

#147: Add some bean definitions at test-context.xml

---

README.md

#155: Update version to 5.0.1.RELEASE in README.md

---

README.md

#156: Update version to 1.0.3.RELEASE in README.md

---

README.md

(cherry picked from commit 9c056e168dc591f9bc9ee2ecdaf2faa44f249ae7)
Please review #155 .

[5.0.x] #155: Update version to 5.0.1.RELEASE in README.md

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

#159: Update to 1.0.4-SNAPSHOT

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

#160: Update to 5.0.2-SNAPSHOT

---

.gitignore

(cherry picked from commit aa3fd4cb451c86e58c6c69ae5edc365113045b79)
Please review #148 .

[5.0.x] #148: Ignore IDEA project file from git management

---

.gitignore

(cherry picked from commit aa3fd4cb451c86e58c6c69ae5edc365113045b79)
Please review #148 .

[1.0.x] #148: Ignore IDEA project file from git management

---

projectName-domain/src/test/resources/test-context.xml

* bean definition of <property-placeholder>
* bean definition of ExceptionLogger
(cherry picked from commit 0ea89bdf9d635f846f99809e58a290170d334a81)
Please review #147 .

[5.0.x] #147: Add some bean definitions at test-context.xml

---

projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloTest.java
projectName-selenium/src/test/resources/META-INF/spring/selenium.properties
projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
projectName-web/src/main/webapp/WEB-INF/views/welcome/home.jsp

add a sample test case. #130

---

infra/jpa/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml

#168: Change default value of 'hibernate.hbm2ddl.auto' ('none' -> '')

---

projectName-web/src/main/webapp/WEB-INF/web.xml

Add config to disable URL rewriting by default #179

---

infra/mybatis3/projectName-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml

* defaultFetchSize
* proxyFactory
Please review #178 .

Apply changes for MyBatis 3.3.0 #178

---

projectName-initdb/pom.xml

Change configuration value of 'onError' option of sql-maven-plugin. (continue -> abort) #193

---

pom.xml

Remove terasoluna-gfw-3rdparty #184

---

pom.xml

(cherry picked from commit 2f3f9e607f548e5fa41ef3e313004099cc9eff58)
Please review #184 .

[5.0.x] Remove terasoluna-gfw-3rdparty #184

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
projectName-web/src/main/resources/META-INF/spring/spring-security.xml

Correspond to the 'Spring Secuity 4.0.' #200

---

projectName-domain/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

Enable the build helper maven plugin.
Please review #176  .

Enable build helper maven plugin #176

---

projectName-web/src/main/resources/ValidationMessages.properties

I've reflected same changes https://github.com/terasolunaorg/terasoluna-gfw-web-blank/pull/163.
Please review and merge #198.

add validation messages for new constraint validation annotations #198

---

projectName-web/pom.xml

change dependency web to web-jsp. issues:#204

---

pom.xml

Update Java version to 1.8 issues:#145

---

pom.xml

Please review #213 
---
e59570b7bb20a366edc7d09f46341aea10584ca7
---

fixed plugin spell #213

---

pom.xml

please review.
---
d6fe58d05c53f1c972f236a64768e2897c0af814
---

fixed plugin spell

---

projectName-web/src/main/resources/META-INF/spring/spring-security.xml

modify 'auto-config' configuration  #201

---

pom.xml

#216
jdbc postgresql version up 9.4-1206-jdbc41

jdbc postgresql version up 9.4-1206-jdbc41 #216

---

pom.xml

#216
jdbc postgresql version up 9.4-1206-jdbc41 5.0.x

jdbc postgresql version up 9.4-1206-jdbc41 5.0.x

---

pom.xml

#216
jdbc postgresql version up 9.4-1206-jdbc41 1.0.x

jdbc postgresql version up 9.4-1206-jdbc41 1.0.x

---

infra/mybatis3/projectName-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
projectName-domain/pom.xml

[5.0.x] add settings for using CGLIB in MyBatis proxyFactory. issues:#220

---

infra/mybatis3/projectName-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
projectName-domain/pom.xml

Please review for additional comment on #220 .

[5.0.x] add comment to dependency. issues:#220

---

pom.xml

remove selenum.version #223

---

CONTRIBUTING.md

Fix a rule for git commit comments #177

---

CONTRIBUTING.md

Please review #177.
(cherry picked from commit 7cb3c83a04ef224b645fce0a8a23250baf229ddc)

[5.0.x] Fix a rule for git commit comments #177

---

CONTRIBUTING.md

Modify a sentence #177

---

CONTRIBUTING.md

Please review #177.
(cherry picked from commit ecc32556c386578ff3d87e7d8a523a09e3a131a0)

[5.0.x] Modify a sentence #177

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

Update to 1.0.5-SNAPSHOT #229

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

Update to 5.0.3-SNAPSHOT #230

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

Update to 5.1.1-SNAPSHOT #231

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

Update to 5.2.0-SNAPSHOT #232

---

README.md

Update version to 1.0.4.RELEASE in README.md #237

---

README.md

Update version to 5.0.2.RELEASE in README.md #238

---

README.md

[5.1.x] Update version to 5.1.0.RELEASE in README.md #239

---

README.md

Update version to 5.1.0.RELEASE in README.md #239

---

ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

Add issue and PR template #244

---

projectName-web/pom.xml

add a dependency to taglibs-standard-jstlel #246

---

projectName-domain/pom.xml
projectName-env/pom.xml

Please review #248 .
Screen display confirmed to be deployed in the local as operation check.

Add the type in the description of the dependency #248

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-web/pom.xml

apply new pom structure #250

---

pom.xml

add new comments to categorize properties #250

---

projectName-domain/pom.xml
projectName-web/pom.xml

modify dependency #250

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

add wordarround to CVE-2016-5007 #254

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

Please review #254.
(cherry picked from commit 2a9e480b3777a4bdbc80668980f399a5faf3c47b)

[5.1.x] add wordarround to CVE-2016-5007 #254

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

Please review #254.
(cherry picked from commit 2a9e480b3777a4bdbc80668980f399a5faf3c47b)

[5.0.x] add wordarround to CVE-2016-5007 #254

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

Please review #254.
(cherry picked from commit 2a9e480b3777a4bdbc80668980f399a5faf3c47b)

[1.0.x] add wordarround to CVE-2016-5007 #254

---

create-maven-archetype-jpa.sh
create-maven-archetype-mybatis3.sh
create-maven-archetype.sh

Make it possible to deploy to maven central #260

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update SNAPSHOT version to 5.3.0-SNAPSHOT.#262

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update SNAPSHOT version to 1.0.6-SNAPSHOT.#262

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update SNAPSHOT version to 5.1.2-SNAPSHOT.#262

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update SNAPSHOT version to 5.2.1-SNAPSHOT.#262

---

README.md

[1.0.x]update version in README.md.#263

---

README.md

[5.1.x]update version in README.md.#263

---

README.md

update version in README.md.#263

---

README.md

[5.2.x]update version in README.md.#263

---

projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

Improve dependency settings to JDBC drivers.#273

---

projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[5.2.x]Improve dependency settings to JDBC drivers.#273

---

projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[5.1.x]Improve dependency settings to JDBC drivers.#273

---

projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[5.0.x]Improve dependency settings to JDBC drivers.#273

---

projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[1.0.x]Improve dependency settings to JDBC drivers.#273

---

pom.xml
projectName-selenium/pom.xml

add selenium dependency. #279

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

fix typo in spring-mvc.xml. #281

---

pom.xml

update Postgresql JDBC Driver version. #282

---

infra/mybatis3/projectName-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml

remove <setting name="aggressiveLazyLoading" value="false" /> in mybatis/mybatis-config.xml.

---

projectName-env/src/main/resources/META-INF/spring/projectName-env.xml

[5.3.x]add settings that DataSourceTransactionManager#setRollbackOnCommitFailure=true in projectName-env.xml

---

projectName-env/src/main/resources/META-INF/spring/projectName-env.xml

Please review #293 .
PR #294 の5.2.x版バックポートです。

[5.2.x]add settings that DataSourceTransactionManager#setRollbackOnCommitFailure=true in projectName-env.xml

---

pom.xml

Modified /pom.xml for Maven Central.#298

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

Add excludedExceptions #304

---

README.md

[5.3.x] explicitly use archetype plugin 2.4 #307

---

README.md

[5.2.x] explicitly use archetype plugin 2.4 #307

---

README.md

[5.1.x] explicitly use archetype plugin 2.4 #307

---

README.md

[5.0.x] explicitly use archetype plugin 2.4 #307

---

README.md

[1.0.x] explicitly use archetype plugin 2.4 #307

---

README.md

[master]Modified version from 5.2.0.RELEASE to 5.3.0.RELEASE.#301

---

README.md

[5.3.x]Modified version from 5.2.0.RELEASE to 5.3.0.RELEASE.#301

---

README.md

[5.2.x]Modified version from 5.2.0.RELEASE to 5.2.1.RELEASE.#301

---

README.md

[1.0.x]Modified version from 1.0.5.RELEASE to 1.0.6.RELEASE.#301

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[master]Update version to 5.4.0-SNAPSHOT.#317

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[5.3.x]Update version to 5.3.1-SNAPSHOT.#317

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[5.2.x]Update version to 5.2.2-SNAPSHOT.#317

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[1.0.x]Update version to 1.0.7-SNAPSHOT.#317

---

pom.xml
projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

fix ojdbc group ID in pom.xml, match officially group ID #324

---

pom.xml
projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[5.3.x ]fix ojdbc group ID in pom.xml, match officially group ID #324

---

pom.xml
projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[5.2.x] fix ojdbc group ID in pom.xml, match officially group ID #324

---

pom.xml
projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[5.0.x] fix ojdbc group ID in pom.xml, match officially group ID #324

---

pom.xml
projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[1.0.x] fix ojdbc group ID in pom.xml, match officially group ID #324

---

ISSUE_TEMPLATE.md

Add Final Solution and Migrating Guide section to Issue Template. #325

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

Remove definition of trimTokens #334

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

[5.3.x] Remove definition of trimTokens #334

---

projectName-env/src/main/resources/logback.xml

add doctype.#332

---

pom.xml
projectName-selenium/pom.xml

remove selenium.version #333

---

pom.xml
projectName-selenium/pom.xml

Please review #333 .
This PR is backport for 5.3.x

[5.3.x] remove selenium.version

---

README.md

fix archetype version in README.md #354

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[5.3.x] fix SNAPSHOT version in pom.xml #356

---

projectName-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html

add br tag to make the error page size 513 bytes or more #361

---

projectName-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html

This PR is backport for 5.3.x .

[5.3.x] add br tag to make the error page size 513 bytes or more #361

---

projectName-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html

This PR is backport for 5.2.x .

[5.2.x] add br tag to make the error page size 513 bytes or more #361

---

projectName-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html

This PR is backport for 5.1.x .

[5.1.x] add br tag to make the error page size 513 bytes or more #361

---

projectName-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html

This PR is backport for 5.0.x .

[5.0.x] add br tag to make the error page size 513 bytes or more #361

---

create-maven-archetype-jpa.sh
create-maven-archetype-mybatis3.sh
create-maven-archetype.sh

be able to select install in addition to deploy #368

---

projectName-web/src/main/webapp/WEB-INF/views/layout/template.jsp

Remove conditional comments #351

---

pom.xml
projectName-selenium/pom.xml

define maven-surefire-plugin version  #371

---

projectName-web/src/main/webapp/WEB-INF/views/layout/template.jsp

[5.3.x] Remove conditional comments #351

---

projectName-web/src/main/webapp/WEB-INF/views/layout/template.jsp

[5.2.x]Remove conditional comments #351

---

projectName-web/src/main/webapp/WEB-INF/views/layout/template.jsp

[5.1.x]Remove conditional comments #351

---

projectName-web/src/main/webapp/WEB-INF/views/layout/template.jsp

[5.0.x]Remove conditional comments #351

---

projectName-web/src/main/webapp/WEB-INF/views/layout/template.jsp

[1.0.x]Remove conditional comments #351

---

create-maven-archetype-jpa.sh
create-maven-archetype-mybatis3.sh
create-maven-archetype.sh

(cherry picked from commit 9aa2c18)
Please review #368.

[5.3.x]be able to select install in addition to deploy #368

---

create-maven-archetype-jpa.sh
create-maven-archetype-mybatis3.sh
create-maven-archetype.sh

(cherry picked from commit 9aa2c18838b0b9ef264541425fb23911bce253a4)
Please review #368.

[5.2.x]be able to select install in addition to deploy #368 

---

create-maven-archetype-jpa.sh
create-maven-archetype-mybatis3.sh
create-maven-archetype.sh

(cherry picked from commit 9aa2c18838b0b9ef264541425fb23911bce253a4)
Conflicts:
create-maven-archetype-jpa.sh
create-maven-archetype-mybatis3.sh
create-maven-archetype.sh
Please review #368 .
This PR is backport for 5.1.x .

[5.1.x] be able to select install in addition to deploy #368

---

create-maven-archetype-jpa.sh
create-maven-archetype-mybatis3.sh
create-maven-archetype.sh

(cherry picked from commit 9aa2c18838b0b9ef264541425fb23911bce253a4)
Conflicts:
create-maven-archetype-jpa.sh
create-maven-archetype-mybatis3.sh
create-maven-archetype.sh
(cherry picked from commit 0ee415263db9b5cb18d3082aeb9fb443c52adc37)
Please review #368 .
This PR is backport for 5.0.x

[5.0.x] be able to select install in addition to deploy #368

---

create-maven-archetype-jpa.sh
create-maven-archetype-mybatis2.sh
create-maven-archetype.sh

(cherry picked from commit 9aa2c18838b0b9ef264541425fb23911bce253a4)
Conflicts:
create-maven-archetype-jpa.sh
create-maven-archetype-mybatis3.sh
create-maven-archetype.sh
(cherry picked from commit 0ee415263db9b5cb18d3082aeb9fb443c52adc37)
Conflicts:
create-maven-archetype-mybatis2.sh
Please review #368 .
This PR is backport for 1.0.x

[1.0.x] be able to select install in addition to deploy #368

---

pom.xml
projectName-selenium/pom.xml

(cherry picked from commit 20079e7)
(cherry picked from commit 3d33d88)
Please review #371.

[5.3.x]define maven-surefire-plugin version #371

---

pom.xml
projectName-selenium/pom.xml

(cherry picked from commit 20079e7)
(cherry picked from commit 3d33d88)
Please review #371.

[5.2.x]define maven-surefire-plugin version #371

---

pom.xml
projectName-domain/pom.xml
projectName-web/pom.xml

Add library for test in pom.xml #360

---

projectName-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
projectName-web/src/main/webapp/WEB-INF/views/layout/template.jsp

format indent #381

---

projectName-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
projectName-web/src/main/webapp/WEB-INF/views/layout/template.jsp

[5.3.x] format indent #381

---

projectName-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
projectName-web/src/main/webapp/WEB-INF/views/layout/template.jsp

[5.2.x] format indent #381

---

projectName-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
projectName-web/src/main/webapp/WEB-INF/views/layout/template.jsp

[5.1.x] format indent #381

---

projectName-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
projectName-web/src/main/webapp/WEB-INF/views/layout/template.jsp

[5.0.x] format indent #381

---

projectName-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/csrfTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
projectName-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
projectName-web/src/main/webapp/WEB-INF/views/layout/template.jsp

[1.0.x] format indent #381

---

README.md

(cherry picked from commit d5e8a07186eec1c4a53fc53e0f662806e84157b9)
Please review #354 .

[5.3.x] fix archetype version in README.md #354

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update to 5.5.0-SNAPSHOT #399

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[5.4.x] update to 5.4.1-SNAPSHOT #399

---

README.md

update version to 5.4.0.RELEASE in README.md #398

---

README.md

fix 5.4.0-RELEASE to 5.4.0.RELEASE in README.md #398

---

README.md

(cherry picked from commit db53b188cff4054366f8b1fcc117931deac4bfad)
Please review #398.

[5.4.x] fix 5.4.0-RELEASE to 5.4.0.RELEASE in README.md #398

---

README.md

update version for readme #411

---

README.md
pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[5.4.x] update version for both readme and pom #411

---

README.md
pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

[5.3.x] update version for both readme and pom #411

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml
projectName-web/src/main/resources/META-INF/spring/applicationContext.xml

update to 5.5.0.RC2-SNAPSHOT #418

---

pom.xml

update postgresql driver #420

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

[5.4.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

[5.3.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

[5.2.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

[5.1.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

[5.0.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348

---

projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

[1.0.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348

---

pom.xml
projectName-web/pom.xml
projectName-web/src/main/resources/META-INF/spring/applicationContext.xml

add comment out the definition of password encoder #424

---

projectName-domain/pom.xml
projectName-web/pom.xml

change definition location from web to domain #424

---

pom.xml

update postgresql #436

---

ISSUE_TEMPLATE.md

Please review #438.
- Delete `Final Solution` 
- Delete `Migrating Guide`
- Add version template into `Fix Version/s`
- Change markdown syntax for listing

update issue template #438

---

ISSUE_TEMPLATE.md
pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

 update to 5.5.1-SNAPSHOT #441 #433

---

projectName-web/src/main/resources/ValidationMessages.properties

apply @ByteSize #443

---

pom.xml
projectName-domain/pom.xml

remove dependency of bcprov-jdk15on #424

---

projectName-web/src/main/resources/ValidationMessages.properties

(cherry picked from commit 92a9862310dbe22b0a73c728bf851acec7d3644d)
Please review #443.

[5.4.x] apply @ByteSize #443

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update to 5.5.2-SNAPSHOT #449

---

ISSUE_TEMPLATE.md
pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update to 5.6.0-SNAPSHOT #449

---

pom.xml

Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/445.

update jdbc driver #445

---

infra/jpa/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
infra/mybatis3/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
projectName-domain/src/main/resources/META-INF/spring/projectName-codelist.xml
projectName-domain/src/main/resources/META-INF/spring/projectName-domain.xml
projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
projectName-domain/src/test/resources/test-context.xml
projectName-env/src/main/resources/META-INF/spring/projectName-env.xml
projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
projectName-web/src/main/resources/META-INF/spring/applicationContext.xml
projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
projectName-web/src/main/resources/META-INF/spring/spring-security.xml

[5.4.x] replace schema location for Spring from http to https #454

---

pom.xml

remove a definition referring to Sonatype Nexus Snapshots #457

---

README.md

(cherry picked from commit a8bfdebf67c6db5951fb178679f26fe0f29782a4)
Please review #459

[5.5.x]update relase version #459

---

README.md

[5.4.x]update release version #459

---

README.md

update relase version #459

---

README.md

Please review #459, https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/459#issuecomment-497540685

fix version to 5.5.1.RELEASE of README #459

---

infra/jpa/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
infra/mybatis3/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
projectName-domain/src/main/resources/META-INF/spring/projectName-codelist.xml
projectName-domain/src/main/resources/META-INF/spring/projectName-domain.xml
projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
projectName-domain/src/test/resources/test-context.xml
projectName-env/src/main/resources/META-INF/spring/projectName-env.xml
projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
projectName-web/src/main/resources/META-INF/spring/applicationContext.xml
projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
projectName-web/src/main/resources/META-INF/spring/spring-security.xml

Please review #454 .
Cherry picked from commit 801d771f8fe10c5453712f58e5bbb8bf6c598c2f .

replace schema location for Spring from http to https #454

---

projectName-web/src/main/resources/ValidationMessages.properties

remove validation messages for common libraries #466

---

projectName-web/src/main/resources/META-INF/spring/applicationContext.xml

Add Argon2PasswordEncoder #472

---

projectName-domain/src/main/resources/META-INF/spring/projectName-codelist.xml

Prepare xml namespace "util" for using SimpleMapCodeList #476

---

pom.xml
projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update JDBC Driver #470

---

projectName-env/src/main/resources/META-INF/spring/projectName-env.xml
projectName-env/src/main/resources/log4jdbc.properties
projectName-env/src/main/resources/logback.xml

remove log4jdbc-remix #469

---

projectName-env/src/main/resources/logback.xml

Provide trace logs about mapped handler method #478

---

projectName-domain/pom.xml
projectName-web/pom.xml

upgrade to hamcrest to 2.x #480

---

pom.xml

upgrade jdbc 42.2.9 #470

---

projectName-env/src/main/resources/logback.xml

change loglevel of Repository to trace to log ResultSet #469

---

README.md
pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update 5.7.0-SNAPSHOT #486

---

README.md
pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update 5.6.1-SNAPSHOT #486

---

pom.xml
projectName-domain/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

(cherry picked from commit 3ae42a4eb4938a43d566f7ec7dada4483d575f1f)
Please review #491.
Original PR #490

[5.6.x]Change the groupId of the OracleJDBCDriver #491

---

README.md

Please review #507
Confirmation method:
- Grep search for "5.6.0." and confirm that there are no omissions.

update 5.6.1.RELEASE in README #507

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update update 5.6.2-SNAPSHOT #506

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update 5.5.3-SNAPSHOT #512

---

projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java

Please review #505 .
Confirmation:
Run tests locally to confirm success.

Switch assertThat to hamcrest's. #505

---

pom.xml

Reverts terasolunaorg/terasoluna-gfw-web-multi-blank#517
Resolve-#520

Revert "[5.6.x]Update the version of the maven plugin #514 (#515)", and update Maven War Plugin #520

---

infra/jpa/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml

fixed EntityManager setting for Hibernate #521

---

infra/jpa/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml

(cherry picked from commit 6ff6b4acfcd57b7bf5b25bbc89239156aaa64a4e)
Please review #523

[5.6.x] fixed EntityManager setting for Hibernate #521

---

pom.xml

(cherry picked from commit c60fc1659d703d7c78b030bb524920080d4a8593)
Please review #531

[5.6.x] set source to maven-javadoc-plugin #493

---

.gitignore

Please review #534 .
Removed unnecessary settings from gitignore.

Remove unnecessary settings from gitignore #534

---

.gitignore

(cherry picked from commit a0cd6733b43e80d63d680e64937b0ae78ad9dd00)
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/536
Removed unnecessary settings from gitignore.

[5.6.x]Remove unnecessary settings from gitignore #534 (#535)

---

README.md

update 5.6.2.RELEASE in README #540

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update to 5.8.0-SNAPSHOT. #542

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update to 5.6.3-SNAPSHOT. #544

---

projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/welcome/HelloController.java

Please review #550 
As described in #550, it is modified to accept only the GET method.

replaced RequestMapping with GetMapping #550

---

pom.xml

update dbunit to 2.7.2 #552

---

pom.xml

(cherry picked from commit 779d640d3faef2836ce0b7adb62752d0bea62488)
Please review #554

update dbunit to 2.7.2 #552 (#553)

---

projectName-domain/pom.xml
projectName-web/pom.xml

Please review #552 
See https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/552#issuecomment-986364298

added poi-ooxml dependency #552

---

projectName-domain/pom.xml
projectName-web/pom.xml

(cherry picked from commit 8de1584b0f052deee443596073794277e995345f)
Please review #554 
See https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/554#issuecomment-987668361

[5.7.x] added poi-ooxml dependency #552 (#556)

---

pom.xml

Match postgresql and ojdbc versions with Spring Boot #558

---

pom.xml

(cherry picked from commit 3b67d105844bb12c8a29319e2fe022c5399beef7)
Please review #560.

Match postgresql and ojdbc versions with Spring Boot #558 (#559) #560

---

projectName-env/src/main/resources/logback.xml

changed log format #562

---

projectName-env/src/main/resources/logback.xml

(cherry picked from commit d4589c18d68140392ce5c8bcfccbe35a9a25dc05)
Please review #564

[5.7.x] changed log format #562 (#563)

---

README.md
pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

update SNAPSHOT to 5.7.2 #566

---

README.md

Change the version in README to the latest version #568

---

.github/ISSUE_TEMPLATE/3-backport-issue.md

improved backport-issue template #570

---

pom.xml

update library and plugin version for 5.7.2 #575

---

pom.xml

Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/575#issuecomment-1414932664 .

Revert to surefire version #575

---

projectName-web/src/main/resources/META-INF/spring/spring-security.xml

fixed FilterSecurityInterceptor setting #578

---

pom.xml

Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/575#issuecomment-1427808623 .

revert failsafe-plugin version #575

---

parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-security.xml

Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/585

Change to default settings

---

parts/JavaConfig/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/app/ApplicationContextConfig.java
parts/XMLConfig/projectName-web/src/main/resources/META-INF/spring/applicationContext.xml

Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/587

Algorithm change in PasswordEncoders #587

---

create-maven-archetype.sh

fix typo #592

---

parts/JSP/projectName-web/pom.xml
parts/Thymeleaf/projectName-web/pom.xml
parts/base/pom.xml
parts/base/projectName-domain/pom.xml
parts/base/projectName-env/pom.xml
parts/base/projectName-initdb/pom.xml
parts/base/projectName-selenium/pom.xml

update SNAPSHOT to 5.8.1. #599

---

parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-security.xml

fix requestMatcher #601

---

README.md
parts/JSP/projectName-web/pom.xml
parts/Thymeleaf/projectName-web/pom.xml
parts/base/pom.xml
parts/base/projectName-domain/pom.xml
parts/base/projectName-env/pom.xml
parts/base/projectName-initdb/pom.xml
parts/base/projectName-selenium/pom.xml

update 5.9.0-SNAPSHOT. #603

---

parts/Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/common/error/CommonErrorController.java

add missing thymeleaf file. #605

---

parts/Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/common/error/CommonErrorController.java

(cherry picked from commit 8bfc01d6c0701c29897763772853e3c1a39dd8a5)
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/607

[5.8.x]add missing thymeleaf file. #605 (#606)

---

README.md
pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

Please review #609 
relate to https://terasolunaorg.atlassian.net/browse/TSF4J5-2397

update 5.7.3-SNAPSHOT. #609

---

README.md
parts/JSP/projectName-web/pom.xml
parts/Thymeleaf/projectName-web/pom.xml
parts/base/pom.xml
parts/base/projectName-domain/pom.xml
parts/base/projectName-env/pom.xml
parts/base/projectName-initdb/pom.xml
parts/base/projectName-selenium/pom.xml

Please review #611 
https://terasolunaorg.atlassian.net/browse/TSF4J5-2397

update 5.8.2-SNAPSHOT #611

---

convert-camelclass.sh
create-maven-archetype-all.sh
create-maven-archetype-javaconfig-jsp-jpa.sh
create-maven-archetype-javaconfig-jsp-mybatis3.sh
create-maven-archetype-javaconfig-thymeleaf-jpa.sh
create-maven-archetype-javaconfig-thymeleaf-mybatis3.sh
create-maven-archetype-xmlconfig-jsp-jpa.sh
create-maven-archetype-xmlconfig-jsp-mybatis3.sh
create-maven-archetype-xmlconfig-thymeleaf-jpa.sh
create-maven-archetype-xmlconfig-thymeleaf-mybatis3.sh
create-maven-archetype.sh

add set -e to shellscript #617

---

testScript/addTestResource.sh
testScript/parts/JSP/projectName-web/src/main/webapp/WEB-INF/views/errortest/otherError.jsp
testScript/parts/JSP/projectName-web/src/test/resources/META-INF/spring/mockmvc.properties
testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/config/SpringMvcMockMvcConfig.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/AccessDeniedErrorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/CsrfTokenErrorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
testScript/parts/Thymeleaf/projectName-web/src/main/webapp/WEB-INF/views/errortest/otherError.html
testScript/parts/Thymeleaf/projectName-web/src/test/resources/META-INF/spring/mockmvc.properties
testScript/parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/AccessDeniedErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/CsrfTokenErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
testScript/parts/XMLConfig/projectName-web/src/test/resources/META-INF/spring/spring-mvc-mockmvc.xml
testScript/parts/base/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/domain/service/errortest/MockTestService.java
testScript/parts/base/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/domain/service/errortest/MockTestServiceImpl.java
testScript/parts/base/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/errortest/MockTestController.java
testScript/parts/base/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/errortest/TestErrorController.java

Please review #615 .
Added test to check internally.
Added a shell to apply after project generation.
JIRA
https://terasolunaorg.atlassian.net/browse/TSF4J5-2806

Add an internal test implementation to the Blank project  #615

---

parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java
parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java
parts/JavaConfig/projectName-domain/src/test/java/xxxxxx/yyyyyy/zzzzzz/config/TestContextConfig.java
parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
parts/XMLConfig/projectName-domain/src/test/resources/test-context.xml
parts/XMLConfig/projectName-web/src/main/resources/META-INF/spring/applicationContext.xml

Please review #619 
Added @EnableAspectJAutoProxy to SpringMvcConfig.
Add the aop:aspectj-autoproxy tag to match the above settings and align the definitions in the XML version.
JIRA
https://terasolunaorg.atlassian.net/browse/TSF4J5-3003

Fixed SpringAOP not working. #619

---

create-maven-archetype.sh

Fixed errors caused by adding set -e. #617

---

testScript/addTestResource.sh
testScript/parts/JSP/projectName-web/src/main/webapp/WEB-INF/views/errortest/otherError.jsp
testScript/parts/JSP/projectName-web/src/test/resources/META-INF/spring/mockmvc.properties
testScript/parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/AccessDeniedErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/CsrfTokenErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
testScript/parts/XMLConfig/projectName-web/src/test/resources/META-INF/spring/spring-mvc-mockmvc.xml
testScript/parts/base/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/domain/service/errortest/MockTestService.java
testScript/parts/base/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/domain/service/errortest/MockTestServiceImpl.java
testScript/parts/base/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/errortest/MockTestController.java
testScript/parts/base/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/errortest/TestErrorController.java

Please review #625 .
Added test to check internally.
Added a shell to apply after project generation.
Regarding BackPort, we have fixed incompatible parts and deleted the JavaConfig version.
JIRA
https://terasolunaorg.atlassian.net/browse/TSF4J5-2803

BackPort:Add an internal test implementation to the Blank project  #625

---

projectName-domain/src/test/resources/test-context.xml
projectName-web/src/main/resources/META-INF/spring/applicationContext.xml
projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml

Please review #627  .
Since the backport will be a version where JavaConfig doesn't exist yet, we only reflected the XML modifications.
JIRA
https://terasolunaorg.atlassian.net/browse/TSF4J5-3240

BackPort:Fixed SpringAOP not working. #627

---

parts/JSP/projectName-web/src/main/webapp/WEB-INF/views/layout/footer.jsp
parts/JSP/projectName-web/src/main/webapp/WEB-INF/views/welcome/home.jsp

Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/630
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-3252.

Add footer #TSF4J5-3252

---

create-maven-archetype-all.sh
create-maven-archetype.sh

Modified shell scripts to add javaconfig version #635

---

parts/JavaConfig/projectName-env/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/app/ProjectNameEnvConfig.java
parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/config/SeleniumContextConfig.java
parts/XMLConfig/projectName-env/src/main/resources/META-INF/spring/projectName-env.xml
parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java

Please review #637
related to https://terasolunaorg.atlassian.net/browse/TSF4J5-3814
Unnecessary import statements were removed.

update boot to 3.2.0 #637

---

testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java

Change helllotest assert content #642

---

testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/resources/META-INF/spring/spring-mvc-mockmvc.xml

Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/641#issuecomment-1888837276 .

fix mock settings #641

---

parts/base/pom.xml
parts/base/projectName-selenium/pom.xml

Please review #648
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-3942
The pom that sets the version of webdrivermanager is changed.

library version up #648

---

parts/base/pom.xml

Please review #650.
relates to [TSF4J5-4104](https://terasolunaorg.atlassian.net/browse/TSF4J5-4104)

add parameters option. #650

---

parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java

Please review #654 
https://terasolunaorg.atlassian.net/browse/TSF4J5-4216

corrected withDefault settings #654

---

testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java

Please review #656.
relates to [TSF4J5-4309](https://terasolunaorg.atlassian.net/browse/TSF4J5-4309).

Format to JDK21. #656

---

testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java

Please review #657.
relates to [TSF4J5-4314](https://terasolunaorg.atlassian.net/browse/TSF4J5-4314).

[5.7.x] Format to JDK21. #657

---

create-maven-archetype.sh

Please review #664.
relates to [TSF4J5-4361](https://terasolunaorg.atlassian.net/browse/TSF4J5-4361).

Added debugging options during deployment #664

---

create-maven-archetype.sh

(cherry picked from commit 741b9701508afe764ff873495bdc5dca3ee0a997)
Please review #666 .
relates to [TSF4J5-4364](https://terasolunaorg.atlassian.net/browse/TSF4J5-4364).

[5.7.x]Added debugging options during deployment #664 (#665)

---

README.md
parts/JSP/projectName-web/pom.xml
parts/Thymeleaf/projectName-web/pom.xml
parts/base/pom.xml
parts/base/projectName-domain/pom.xml
parts/base/projectName-env/pom.xml
parts/base/projectName-initdb/pom.xml
parts/base/projectName-selenium/pom.xml

Please review #669.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4332

update 5.10.0-SNAPSHOT. #669

---

parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java

fixed how AntPathRequestMatcher is implemented #668

---

README.md
parts/JSP/projectName-web/pom.xml
parts/Thymeleaf/projectName-web/pom.xml
parts/base/pom.xml
parts/base/projectName-domain/pom.xml
parts/base/projectName-env/pom.xml
parts/base/projectName-initdb/pom.xml
parts/base/projectName-selenium/pom.xml

Please review #672.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4380

update 5.9.1-SNAPSHOT. #672

---

README.md
pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

Please review #674.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4401

[5.7.x]update 5.7.4-SNAPSHOT. #674

---

parts/base/projectName-env/src/main/resources/logback.xml

Please review #676.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4349

fix logback settings #676

---

parts/base/projectName-env/src/main/resources/logback.xml

Please review #678
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-2899

update Hibernate log output settings. #678

---

projectName-env/src/main/resources/logback.xml

TSF4J5-4349
(cherry picked from commit 2f91d2f8311bb5987d0a294443eb99c2a21c2d4d)
Please review #680 .
related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4610

[5.7.x]fix logback settings #676 (#677)

---

projectName-env/src/main/resources/logback.xml

Please review #682 .
related to https://terasolunaorg.atlassian.net/browse/TSF4J5-2912

update Hibernate log output settings. #682

---

projectName-env/src/main/resources/logback.xml

Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/682#issuecomment-2151143464
related to https://terasolunaorg.atlassian.net/browse/TSF4J5-2912

changed the logger class to one compatible with hibernate 5. #682

---

testScript/parts/JavaConfig/projectName-selenium/src/test/java/.gitkeep
testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/config/SeleniumContextConfig.java
testScript/parts/XMLConfig/projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/ChromeDriverFactoryBean.java
testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/EdgeDriverFactoryBean.java
testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/FirefoxDriverFactoryBean.java
testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/HeadlessWebDriverManagerFactoryBean.java
testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/WebDriverManagerFactoryBean.java
testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/WebDriverType.java
testScript/parts/base/projectName-selenium/src/test/resources/META-INF/spring/selenium.properties
testScript/parts/base/projectName-selenium/src/test/resources/wdm.properties

Please review #685.
relates to [TSF4J5-4630](https://terasolunaorg.atlassian.net/browse/TSF4J5-4630).

Make it headless compatible. #685

---

parts/JSP/projectName-web/src/main/webapp/WEB-INF/views/common/include.jsp
parts/XMLConfig-JPA/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
parts/XMLConfig-JSP/projectName-web/src/main/webapp/WEB-INF/web.xml
parts/XMLConfig-MyBatis3/projectName-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
parts/XMLConfig-MyBatis3/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
parts/XMLConfig-Thymeleaf/projectName-web/src/main/webapp/WEB-INF/web.xml
parts/XMLConfig/projectName-domain/src/main/resources/META-INF/spring/projectName-codelist.xml
parts/XMLConfig/projectName-domain/src/main/resources/META-INF/spring/projectName-domain.xml
parts/XMLConfig/projectName-domain/src/test/resources/test-context.xml
parts/XMLConfig/projectName-env/src/main/resources/META-INF/spring/projectName-env.xml
parts/XMLConfig/projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
parts/XMLConfig/projectName-web/src/main/resources/META-INF/spring/applicationContext.xml

Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/691#issuecomment-2303380242
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-4885

minor formatting corrections #691

---

infra/jpa/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
infra/mybatis3/projectName-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
infra/mybatis3/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
projectName-domain/src/main/resources/META-INF/spring/projectName-codelist.xml
projectName-domain/src/main/resources/META-INF/spring/projectName-domain.xml
projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
projectName-domain/src/test/resources/test-context.xml
projectName-env/src/main/resources/META-INF/spring/projectName-env.xml
projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
projectName-web/src/main/resources/META-INF/spring/applicationContext.xml
projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
projectName-web/src/main/resources/META-INF/spring/spring-security.xml

Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/692#issuecomment-2311868143
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-4893

[5.7.x] minor formatting corrections #692

---

projectName-web/src/main/webapp/WEB-INF/web.xml

Please review #697 
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-5010

[5.7.x] Changed to Servlet 4.0. #697

---

testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java

Please review #699.
relates to [TSF4J5-5125](https://terasolunaorg.atlassian.net/browse/TSF4J5-5125).

Change the way Mockito rules are configured.

---

LICENSE.txt

Please review #701 
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-5179

add LICENSE.txt #701

---

LICENSE.txt

[5.7.x] add LICENSE.txt #703

---

parts/JSP/projectName-web/pom.xml
parts/Thymeleaf/projectName-web/pom.xml
parts/base/pom.xml
parts/base/projectName-domain/pom.xml
parts/base/projectName-env/pom.xml
parts/base/projectName-initdb/pom.xml
parts/base/projectName-selenium/pom.xml

add <developers> and <scm> on pom.xml #705

---

testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java

This reverts commit 87179940207a42d112b58fcba3a2b3b1ba1979d0.
Please review #709.

Apply Spring Boot 3.4.0-RC1 #709

---

pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

add <developers> and <scm> on pom.xml #707

---

parts/base/pom.xml
parts/base/projectName-initdb/pom.xml

Please review #711 
Fixed how to specify war generated by maven-war-plugin according to the documentation.
https://maven.apache.org/plugins/maven-war-plugin/usage.html#invocation-of-war-exploded-goal

update the plugin version #711

---

projectName-web/src/main/resources/META-INF/spring/applicationContext.xml

Please review #713 .
related to [TSF4J5-5881](https://terasolunaorg.atlassian.net/browse/TSF4J5-5881)

fix bcprov comment. #713

---

parts/JavaConfig-MyBatis3/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/app/ProjectNameInfraConfig.java
parts/JavaConfig/projectName-domain/src/test/java/xxxxxx/yyyyyy/zzzzzz/config/TestContextConfig.java
parts/JavaConfig/projectName-env/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/app/ProjectNameEnvConfig.java
parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
parts/base/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/welcome/HelloController.java

Please review #691.
relates to [TSF4J5-5862](https://terasolunaorg.atlassian.net/browse/TSF4J5-5862).

modified import text and formatting #691

---

parts/base/pom.xml

Please review #719
relate to [TSF4J5-5962](https://terasolunaorg.atlassian.net/browse/TSF4J5-5962)

remove extra vesion define, update jdbc version. #719

---

pom.xml

Please review #721 .
releta to [TSF4J5-5975](https://terasolunaorg.atlassian.net/browse/TSF4J5-5975)

remove extra definition, update jdbc. #721

---

parts/JSP/projectName-web/pom.xml
parts/Thymeleaf/projectName-web/pom.xml
parts/base/pom.xml
parts/base/projectName-domain/pom.xml
parts/base/projectName-initdb/pom.xml
parts/base/projectName-selenium/pom.xml

Please review #723 
relate to [TSF4J5-6120](https://terasolunaorg.atlassian.net/browse/TSF4J5-6120)

update ojdbc driver. #723

---

pom.xml

Please review #725 
relate to [TSF4J5-6129](https://terasolunaorg.atlassian.net/browse/TSF4J5-6129)

update ojdbc driver. #725

---

README.md
parts/JSP/projectName-web/pom.xml
parts/Thymeleaf/projectName-web/pom.xml
parts/base/pom.xml
parts/base/projectName-domain/pom.xml
parts/base/projectName-env/pom.xml
parts/base/projectName-initdb/pom.xml
parts/base/projectName-selenium/pom.xml

5.11.0-SNAPSHOT #728

---

README.md
parts/JSP/projectName-web/pom.xml
parts/Thymeleaf/projectName-web/pom.xml
parts/base/pom.xml
parts/base/projectName-domain/pom.xml
parts/base/projectName-env/pom.xml
parts/base/projectName-initdb/pom.xml
parts/base/projectName-selenium/pom.xml

5.10.1-SNAPSHOT #729

---

README.md
pom.xml
projectName-domain/pom.xml
projectName-env/pom.xml
projectName-initdb/pom.xml
projectName-selenium/pom.xml
projectName-web/pom.xml

5.7.5-SNAPSHOT #730

---

parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java
parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java

Modify Javadoc #727

---

parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-security.xml

Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/738 .

Fixed redundant bean definitions #738

---

parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java
parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java

(cherry picked from commit 9f9f84ef9a81100d42f70d2da08de28cc984fc01)
Please review #735.

[5.10.x] Modify Javadoc #735

---

parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-security.xml

(cherry picked from commit 985537caddcaf1ff2a0ca1c6b4144442240ab802)
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/739 .
https://terasolunaorg.atlassian.net/browse/TSF4J5-6345

Fixed redundant bean definitions #738 (#737)

---

parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-security.xml

Please review #753.
* Changed from AntPathRequestMatcher to PathPatternRequestMatcher
relates to [TSF4J5-6884](https://terasolunaorg.atlassian.net/browse/TSF4J5-6884)

Apply Spring Boot 4.0.0-M1

---

parts/JSP/projectName-web/pom.xml
parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
parts/Thymeleaf/projectName-web/pom.xml
parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
parts/base/projectName-domain/pom.xml
parts/base/projectName-selenium/pom.xml
testScript/addTestResource.sh
testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/AccessDeniedErrorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/CsrfTokenErrorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
testScript/parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
testScript/parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/AccessDeniedErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/CsrfTokenErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java

Please review #752 
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-6950

migration from Hamcrest to AssertJ #752

---

testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java

minor corrections #752
